### PR TITLE
Added zpp::bits v2.0

### PR DESCRIPTION
**Pull request by eyalz800**
I kind of made a new library that is a complete refactor of the zpp::serializer library, wonder if you mind merging it to see the official comparison

### CODE REVIEW

**Comment by eyalz800** [comment]
@fraillt any chance we can replace the old library I have in your benchmark with this one ?

**Comment by fraillt** [comment]
Sure, why not :) but I don't understand what do you mean by "replace"? 
I see that you keep old "zpp" and add new one "zpp_bits". 
Do you want to still keep "zpp"?

**Comment by eyalz800** [comment]
@fraillt I'll submit a separate PR to remove the old one

**Comment by eyalz800** [comment]
P.S I just noticed your readme mentions GCC 10, for the bit cast I need gcc-11 and clang-12 at least I believe.

**Comment by fraillt** [comment]
Compiler is not a problem :)
I don't mind if you would also update README file with your execution times.

BTW, I tested your branch, and zpp_bits performance is out of this world. Could you explain were the secret lies? :)

**Comment by eyalz800** [comment]
@fraillt Hi, I definitely will explain it, I'm just out of home right now I'll write the explanation here when I get some time

**Comment by eyalz800** [comment]
@fraillt if you don't want to update the readme, do you mind posting your results here and I will place them in the readme, I just have an arm MacBook and for some reason my setup does not compile all the tested libraries

**Comment by eyalz800** [comment]
So about the explanation of how this achieved good results - I didn't actually do a lot special to achieve good results but I made sure to pay attention to the following details:
1. No undefined behaviors, it sounds strange but any reinterpret cast between two different pointer types could potentially lead to undefined behavior or confuse the compiler, so I avoided that completely. 
2. Everything is statically typed and templated to the exact scenario - when writing to std::vector the std::vector type substituted statically in the archive, otherwise span is used. There is actually more to do in that regard for static arrays (such as using span with fixed extent).
3. When writing objects that can be serialized as bytes because they are trivially copyable and there is no padding involved, serialization becomes a memcpy which is faster. (this includes also the fundamental and enumeration types.)
4. Make sure the compiler can inline everything and see through everything, I helped it with inline attributes where I suspected there would not be inlining.
5. I just put all the stuff in godbolt so you can investigate: https://godbolt.org/z/GK8xPz4P3

@fraillt

**Comment by fraillt** [comment]
Thanks for explanation!

**Pull request merged**
