### PR TITLE
Compression ratio

### PR DESCRIPTION
**Pull request by TotalKrill**
I chose to remove all c++ specific overhead in vectors and std::string and only include the actual data used. 

Dont really know if it makes sense, I was mainly just curious to be able to compare the compression ratio

### CODE REVIEW

**Comment by fraillt** [comment]
Thank you for your contribution, maybe it's good idea to include pure data usage, but there are few issues with your implementation:
* `Monster` has two `string` containers, `monster->name` and `monster->weapon->name`
* In order to calculate pure data usage `datasize_bytes - container_overhead` is not enough, because you also need to store each container size to correctly deserialize data. E.g. imagine two strings "aba" and "bab", if you directly serialize them without any meta data, you get "ababab", and there is no way to know how to deserialize them back correctly, so you need write size for each container, before writing data. Writing size space-efficiently is also tricky.
* `datasize_bytes += sizeof(MyTypes::Monster);` is bigger than adding all elements separately, because of padding between elements.
So if you do everything correctly and write size efficiently for containers, you'll end up with the same size as `bitsery` implementation :)

**Comment by TotalKrill** [comment]
Thanks for having a look! Mainly i just wanted some kind of metric on how the serializing actually performs in areas where the size of a sent object is very important, like in embedded systems over low-rate wireless.

1. Yeah true! missed that one!

2. I agree. I think that maybe I need to find exactly what should be the "pure data", I think that maybe the most naive approach at trying to send an object as a binary version should be considered as the "pure data" and use that as metric to how a serializer is storing it. Maybe that means that the pure data should include the container overhead as well. Basically getting what one would expect from doing static_cast<uint8_t[]>( object ) and having it actually work :)

3. But that is one thing that i find interesting, that the padding between elements actually takes memory. So when it should be sent, this should not be there, and I consider this as part of the serializers work, maybe this is wrong though. But like protobuf and its varint. It actually takes the value of integers into account when serializing, so a uint64_t would be different sizes depending on its value, and that is a way of handling the zero-padding between values even if they are actually next to each other in memory, so I put the alignment padding in the same category!

**Comment by fraillt** [comment]
Yes, you are right, padding is handled by serializer, so if you have structure like this:
```cpp
struct Padding{
    int8_t a1;
    int64_t b8;
    int8_t c1;
};
```
and do `cout << sizeof(Padding)` then you'll get `24` bytes, but serializer should only write 1+8+1=10 bytes.
However, all serializer have all kinds of tricks to reduce size. For example `flatbuffers` have default values, `protobuf` compress integers using `zigzag-encoding`, bitsery compresses container sizes, etc...

If all you care is to know what serializer can compress data the most, it is `bitsery`, because it is the only one that enables you to explicitly define how data should be written, if you know certain characteristics about it. Looking at `test_bitsery_compression` you'll see that Vec3 is writing differently, 
If you know your data and your restrictions, you customize further than this.

**Comment by fraillt** [comment]
I'm closing this, you can compare other serializers size ratio with #3.

**Pull request closed without merging**
