### PR TITLE
Monster with image

### PR DESCRIPTION
**Pull request by Luny-S**

### CODE REVIEW

**Comment by niXman** [comment]
my apologies, but why add OpenCV to this test and to test `cv::imencode` and `cv::imdecode` functions here?

for any serialization library, images - just a buffers with random bytes inside.
if you want to test serialization of buffer one more time - just use `std::vector<char>` or `std::string` and fill the buffer with any bytes.

**Comment by niXman** [comment]
> if you want to test serialization of buffer one more time

exactly one more time, because the test of serializing vector of bytes and strings we already have here:
https://github.com/fraillt/cpp_serializers_benchmark/blob/master/testing_core/testing/types.h#L55
https://github.com/fraillt/cpp_serializers_benchmark/blob/master/testing_core/testing/types.h#L68
https://github.com/fraillt/cpp_serializers_benchmark/blob/master/testing_core/testing/types.h#L69

**Comment by ASil-Scanway** [comment]
I apologize. This MR to main repository was not supposed to be created. It was my quick attempt to test how these libraries behave with large binary data.

**Comment by niXman** [comment]
ah, got it!

then you can just ask the libs developers =)

**Comment by ASil-Scanway** [comment]
I can't close this MR myself. I would like to ask someone with permissions to close/delete this thread.

**Comment by niXman** [comment]
@fraillt ^^^

**Comment by eyalz800** [comment]
@aleksander-sil interesting test, I’m following the results on your main page

**Comment by fraillt** [comment]
Thanks for sharing results! but as I understand we can close it :)

**Pull request closed without merging**
